name: anonaddy
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.1.0+61

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Formatting
  intl: ^0.19.0

  # Icons
  cupertino_icons: ^1.0.8

  # UI Components
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  shimmer: ^3.0.0
  fluttertoast: ^8.2.6
  fl_chart: ^0.68.0
  wolt_modal_sheet: ^0.6.1
  flutter_onboarding_slider: ^1.0.11

  # Internet Connectivity
  dio: ^5.4.2+1
  url_launcher: ^6.3.0
  connectivity_plus: ^5.0.2

  # Storage
  flutter_secure_storage: ^9.2.2

  # Security
  secure_application: ^4.0.1
  local_auth: ^2.2.0

  # State Management
  flutter_riverpod: ^2.5.1

  # Testing
  mocktail: ^1.0.4

  # App Package
  package_info_plus: ^8.0.0
  flutter_native_splash: ^2.4.0

  # Monetization
  purchases_flutter: ^6.25.0
  purchases_ui_flutter: ^6.25.0

  # Routing
  auto_route: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#19216C"
  color_dark: "#19216C"
  image: assets/images/splash_image.png
  image_dark: assets/images/splash_image.png

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
