name: anonaddy
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.7.11+33

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.1

  # UI Components
  flutter_svg: ^1.0.3
  lottie: ^1.0.1
  animations: ^2.0.0
  shimmer: ^2.0.0
  fluttertoast: ^8.0.8
  fl_chart: ^0.41.0
  modal_bottom_sheet: ^2.0.0

  # Internet Connectivity
  http: ^0.13.1
  url_launcher: ^6.0.3
  connectivity: ^3.0.2

  # Storage
  flutter_secure_storage: ^5.0.2
  hive: ^2.0.4
  hive_flutter: ^1.0.0

  # Security
  secure_application: ^3.7.1
  local_auth: ^1.1.4

  # State Management
  flutter_riverpod: ^1.0.3
  flutter_phoenix: ^1.0.0

  # Data Modeling
  json_annotation: ^4.4.0

  # Testing
  mockito: ^5.1.0

  # App Package
  package_info_plus: ^1.3.0
  flutter_native_splash: ^2.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.17.12
  build_runner: ^2.0.6
  hive_generator: ^1.1.0
  json_serializable: ^6.1.4

flutter_native_splash:
  color: "#19216C"
  color_dark: "#19216C"
  image: assets/images/splash_image.png
  image_dark: assets/images/splash_image.png

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
