import 'package:anonaddy/services/access_token/access_token_service.dart';
import 'package:anonaddy/services/alias/alias_service.dart';
import 'package:anonaddy/services/biometric_auth/biometric_auth_service.dart';
import 'package:anonaddy/services/connectivity/connectivity_service.dart';
import 'package:anonaddy/services/data_storage/offline_data_storage.dart';
import 'package:anonaddy/services/data_storage/search_history_storage.dart';
import 'package:anonaddy/services/domain_options/domain_options_service.dart';
import 'package:anonaddy/services/domains/domains_service.dart';
import 'package:anonaddy/services/recipient/recipient_service.dart';
import 'package:anonaddy/services/user/user_service.dart';
import 'package:anonaddy/services/username/username_service.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final usernameServiceProvider = Provider((ref) => UsernameService());
final userServiceProvider = Provider((ref) => UserService());
final aliasServiceProvider = Provider((ref) => AliasService());
final domainOptionsServiceProvider = Provider((ref) => DomainOptionsService());
final accessTokenServiceProvider = Provider((ref) => AccessTokenService());
final recipientServiceProvider = Provider((ref) => RecipientService());
final domainsServiceProvider = Provider((ref) => DomainsService());
final biometricAuthServiceProvider = Provider((ref) => BiometricAuthService());
final connectivityServiceProvider = Provider((ref) => ConnectivityService());
final offlineDataProvider = Provider((ref) => OfflineData());
final storageProvider = Provider((ref) => SearchHistoryStorage());
